[[main]]
  name = "Get Started"
  url = "/get-started/"
  weight = 10

[[main]]
  name = "Build Reports"
  url = "/build-reports/"
  weight = 20

[[main]]
  name = "Troubleshoot"
  url = "/troubleshoot/"
  weight = 30
