copyright = "OfficeConnect Pro"

github_repo = "https://github.com/s-mcintosh/officeconnectpro"
github_project_repo = "https://github.com/s-mcintosh/officeconnectpro"
github_branch = "main"

offlineSearch = true
prism_syntax_highlighting = false

[ui]
breadcrumb_disable = false
navbar_logo = false
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_search_disable = false
navbar_translucent_over_cover_disable = true

[ui.feedback]
enable = false

[ui.readingtime]
enable = false
