copyright = "OfficeConnectPro"

offlineSearch = true
prism_syntax_highlighting = false

[ui]
breadcrumb_disable = false
navbar_logo = true
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_search_disable = false
navbar_translucent_over_cover_disable = true
showLightDarkModeMenu = true

[ui.feedback]
enable = false

[ui.readingtime]
enable = false

[links]
  [[links.user]]
    name = "GitHub"
    url = "https://github.com/s-mcintosh"
    icon = "fab fa-github"
  [[links.user]]
    name = "YouTube"
    url = "https://www.youtube.com/@officeconnectpro"
    icon = "fab fa-youtube"
  [[links.user]]
    name = "Ko-fi"
    url = "https://ko-fi.com/smcintosh"
    icon = "fas fa-mug-hot"
